### ISSUE TITLE
Build an automation to support EM workflows

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#101]
EMs who use GitHub are finding that they want to adopt workflows that require a fair bit of manual clicking. Maybe we can build out something in eng-pipes that let's them self-serve declare rulesets?

Use cases are things like adding all issues in a repo to a board, labeling or updating field info on a board for an issue.

**Comment by bruno-garcia** [comment]
I've been using this to get all issues in the configured repos to be assigned to a project.
And issues in another configuration, that have a specific label, to be assigned on that same project.

The goal is to get all work of a specific team (that uses a single project) show up automatically, regardless what repo has that issue landing in. And it's usually either: All issues in a repo belong to the team, or in monorepos: issues with a certain label belong to the team.

**Comment by bruno-garcia** [comment]
To update, I'm back at the approach I was using before but @hazat now generalized this into Sentry's org: https://github.com/getsentry/sentry-project-automation/

**Comment by chadwhitacre** [comment]
Is https://github.com/getsentry/sentry-project-automation even necessary anymore now that "auto-add to project" has shipped? Afaict that's the only feature of `sentry-project-automation`.

<img width="923" alt="auto-add" src="https://user-images.githubusercontent.com/134455/219167384-6f7828f9-1556-406d-b583-3afaa4300503.png">

**Comment by chadwhitacre** [comment]
Closing this based on GitHub investing in workflows so we don't have to.
