### ISSUE TITLE
`Type: Epic` automation setup request

### ISSUE THREAD

**Issue by HazAT** [getsentry/team-ospo#102]
### From

Team: Web Frontend

### To

WEB

Please while being at it - change the team label from 

`Team: Web Frontend`

to

`Team: Web SDKs - Frontend`
to match with the backend team.

**Comment by chadwhitacre** [comment]
`Team: Web SDKs - Frontend`

Already [done](https://github.com/getsentry/sentry/labels/Team%3A%20Web%20SDKs%20-%20Frontend)?

**Comment by chadwhitacre** [comment]
Done.
