### ISSUE TITLE
`Type: Epic` automation setup request

### ISSUE THREAD

**Issue by logicalbomb** [getsentry/team-ospo#105]
### From

Team: Issue Platform

### To

ISP

**Comment by chadwhitacre** [comment]
Okay, it did create dupes. I've closed the old ones and confirmed that the new ones are the ones linked on the GitHub issues (https://github.com/getsentry/sentry/issues/43973, https://github.com/getsentry/sentry/issues/42044).

**Comment by chadwhitacre** [comment]
Guess we're set! 👍

**Comment by chadwhitacre** [comment]
Drat. Not out of the woods. Now both sets of Jira issues are seemingly linked to the GitHub issues, so that when I closed out the Jira issue that I don't want, it closed the GitHub issue that we _do_ want. 🤔

**Comment by chadwhitacre** [comment]
But now that those are deleted, maybe reopening the GitHub issue will be fine? There's nothing to reopen in Jira, ISP-95 is still open.

**Comment by chadwhitacre** [comment]
Dang it. Unito closed the GH issues again, I think because it sees the Jira side as deleted. 🤔

Options I'm seeing are:

1. Start over by recreating the GitHub issues and letting the new automation pick them up.
2. Contact Unito support to see if they can help break the bad connection.

**Comment by chadwhitacre** [comment]
I've sent a message to Unito support, let's see how fast and helpful they are.

**Comment by chadwhitacre** [comment]
Confirmed with Dan that we'll give Unito a chance to clean this up for us before going with (1).

**Comment by chadwhitacre** [comment]
sadpanda
