### ISSUE TITLE
Set up weekly TTR dashboard for Support

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#114]
@souredoutlook wants to see weekly TR performance.

**Comment by chadwhitacre** [comment]
Made a start: https://sentryio.cloud.looker.com/dashboards/1113.

**Comment by chadwhitacre** [comment]
Need to understand how 1113 relates to 401, seeing some discrepancies. Which date is which?

**Comment by chadwhitacre** [comment]
You good here, @souredoutlook? Need anything else?

**Comment by souredoutlook** [comment]
Thank you @chadwhitacre this is good!
