### ISSUE TITLE
Add triage bot to additional repos

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#118]
@hazat requests:

https://github.com/getsentry/sentry-webpack-plugin
https://github.com/getsentry/sentry-javascript-bundler-plugins
https://github.com/getsentry/sentry-elixir
https://github.com/getsentry/sentry-go

**Comment by chadwhitacre** [comment]
[We have docs for this now](https://www.notion.so/sentry/GitHub-Automations-758255bbe26041518d831e8b66aae705).

**Comment by hubertdeng123** [comment]
`sentry-webpack-plugin` is archived, so I don't think it's necessary to add this one

**Comment by hubertdeng123** [comment]
https://github.com/getsentry/eng-pipes/pull/731 should do the trick. Full list includes
- `sentry-elixir`
- `sentry-go`
- `sentry-unreal`
- `sentry-electron`

I don't remember exactly when `sentry-unreal` and `sentry-electron` were requested, but they are defined in security-as-code. We'll need to have some sort of automation to update that with `github-orgs.yml`

**Comment by hubertdeng123** [comment]
@chadwhitacre would you be able to add the bot to the repos above?

**Comment by chadwhitacre** [comment]
Done!

**Comment by hubertdeng123** [comment]
this should be finished now. closing
