### ISSUE TITLE
Move stalebot to eng-pipes

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#139]
Move stalebot to eng-pipes
- [x] https://github.com/getsentry/eng-pipes/pull/451
- [x] https://github.com/getsentry/eng-pipes/pull/506
- [x] https://github.com/getsentry/ops/pull/7299
- [x] removing stale.yml in repos
  - [x] https://github.com/getsentry/sentry/pull/52737
  - [x] https://github.com/getsentry/sentry-docs/pull/7418
  - [x] arroyo (doesn't have stale)
  - [x] cdc (doesn't have stale)
  - [x] craft (doesn't have stale)
  - [x] relay (doesn't have stale)
  - [x] responses (doesn't have stale)
  - [x] https://github.com/getsentry/self-hosted/pull/2255
  - [x] sentry-native (doesn't have stale)
  - [x] snuba (doesn't have stale)
  - [x] snuba-sdk (doesn't have stale)
  - [x] symbolic (doesn't have stale)
  - [x] symbolicator (doesn't have stale)
  - [x] wal2json (doesn't have stale)
  - [x] https://github.com/getsentry/sentry-javascript/pull/8519
  - [x] https://github.com/getsentry/sentry-python/pull/2245
  - [x] https://github.com/getsentry/sentry-php/pull/1567
  - [x] https://github.com/getsentry/sentry-laravel/pull/730
  - [x] https://github.com/getsentry/sentry-symfony/pull/746
  - [x] https://github.com/getsentry/sentry-ruby/pull/2069
  - [x] https://github.com/getsentry/sentry-cocoa/pull/3143
  - [x] sentry-java (doesn't have stale)
  - [x] https://github.com/getsentry/sentry-react-native/pull/3183
  - [x] sentry-unity (doesn't have stale)
  - [x] sentry-dart (doesn't have stale)
  - [x] sentry-android-gradle-plugin (doesn't have stale)
  - [x] sentry-dotnet (doesn't have stale)
  - [x] sentry-dart-plugin (doesn't have stale)
  - [x] https://github.com/getsentry/.github/pull/127

**Comment by hubertdeng123** [comment]
Moved initialize logic of stalebot to eng-pipes, but due to missing logic around ignoring issues with `Status: Backlog` and `Status: In Progress`, decided to move this item down in priority given that we are going to remove those labels later.

**Comment by chadwhitacre** [comment]
Also https://github.com/getsentry/.github/tree/main/.github/workflows.

**Comment by hubertdeng123** [comment]
> Also https://github.com/getsentry/.github/tree/main/.github/workflows.
good call

**Comment by hubertdeng123** [comment]
put one up for .github!
https://github.com/getsentry/.github/pull/127
