### ISSUE TITLE
Evaluate self-hosted ⇒ SaaS migration project

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#151]
We're being invited to expand the scope of our ownership of self-hosted ⇒ SaaS migration.

- [One-click SaaS migration from OSS🔒](https://www.notion.so/sentry/One-click-SaaS-migration-from-OSS-fc316d16efc545928c38b4031735decc) – BYK's old proposal
- [Sentry Export / Import PRD🔒](https://www.notion.so/sentry/Sentry-Export-Import-PRD-57c068fc06e9421abc83ef99e3f06214) – Mike/Gautham's notes
- [Google Doc scratchpad🔒](https://docs.google.com/document/d/1O1g3BFP-Vv4SW6X3OYe66ZMBg6sxKWJmIkQmmpqdx00/edit?usp=sharing) – Chad's notes
- [Migration Tool Notes🔒](https://www.notion.so/sentry/Migration-Tool-Notes-833d449e22224634ae034b1a9a5e23bc) – Alex's notes

**Comment by BYK** [comment]
Don't remember the details of `load-it-up` (and it is not publicly available) but if my memory is accurate, you'll need a combination of the two for max efficiency :)

Also, ideally you'd find a way for a one-click migration:

1. Click a button on Self-Hosted that takes you to a page pre-filled with your org details (might be a challenge for multi-org installs)
2. On this page, you quickly sign up and get some instructions for dual-writing your events
3. With the dual-writing, you determine a cut-off point for migrations/backup data
4. You get a special link/token from SaaS and use it on self-hosted which starts sending data to SaaS

Note that none of these scripts do these. Also keep in mind that in the original migrations, they only migrated orgs, users, and projects not past data. I'm not sure if that's the best approach as you lose lots of history.

**Comment by chadwhitacre** [comment]
We've decided to proceed with this. I'm going to close this out and ask @azaslavsky to start a new issue for the epic.
