### ISSUE TITLE
Validation pipeline works on cloudbuild

### ISSUE THREAD

**Issue by azaslavsky** [getsentry/team-ospo#199]

**Comment by chadwhitacre** [comment]
🙃 

<img width="1198" alt="Screenshot 2023-09-13 at 5 07 47 PM" src="https://github.com/getsentry/team-ospo/assets/134455/0ae46018-a607-4d08-9f89-ad9b516421a7">

<img width="1191" alt="Screenshot 2023-09-13 at 5 09 05 PM" src="https://github.com/getsentry/team-ospo/assets/134455/931f5dd0-81cf-47ab-8bfd-ffeb8d7b8e40">
