### ISSUE TITLE
Upgrade to FSL 1.1

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#233]
Previous: https://github.com/getsentry/team-ospo/issues/212

- [x] https://github.com/getsentry/fsl.software/issues/23
- [x] Sentry
  - [x] https://github.com/getsentry/sentry/pull/65879
  - [x] https://github.com/getsentry/self-hosted/pull/2835
  - [x] https://github.com/getsentry/sentry-docs/pull/9255
  - [x] https://github.com/getsentry/relay/pull/3172
  - [x] https://github.com/getsentry/snuba/pull/5587
  - [x] https://github.com/getsentry/snuba-sdk/pull/178
  - [x] https://github.com/getsentry/vroom/pull/417
  - [x] https://github.com/getsentry/timeseries-analysis-service/pull/253
  - [x] https://github.com/getsentry/develop/pull/1170
  - [x] https://github.com/getsentry/sentry-kafka-schemas/pull/223
  - [x] https://github.com/getsentry/usage-accountant/pull/32
- [x] Codecov
  - [x] https://github.com/codecov/codecov-api/pull/423
  - [x] https://github.com/codecov/codecov-gateway/pull/90
  - [x] https://github.com/codecov/shared/pull/137
  - [x] https://github.com/codecov/gazebo/pull/2626
  - [x] https://github.com/codecov/self-hosted/pull/33
  - [x] https://github.com/codecov/relay/pull/18
  - [x] https://github.com/codecov/worker/pull/291
- [x] https://github.com/getsentry/static-sites/pull/2349
- [x] docs - https://github.com/getsentry/sentry-docs
- [x] dev docs - https://github.com/getsentry/develop
- [x] Notion
    - [x] https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42 🔒

**Comment by chadwhitacre** [comment]
Hacking it with a script whose current state is:

```sh
#!/usr/bin/env zsh

one () {
  cd $1
  git reset --hard
  notice=$(grep Copyright LICENSE.md | sed -e 's/-2023/-2024/' | sed -e 's/ 2023/ 2023-2024/') 
  echo $notice
  cp /Users/chadwhitacre/Desktop/LICENSE.md .
  sed -e "s/NOTICE/$notice/" -i '' LICENSE.md
  git diff
  cd ../..
}

one getsentry/relay/
exit
one getsentry/snuba/
one getsentry/snuba-sdk/
one getsentry/vroom/
one getsentry/timeseries-analysis-service/
one getsentry/develop/
one getsentry/sentry-kafka-schemas/
one getsentry/usage-accountant/
one codecov/codecov-api/
one codecov/codecov-gateway/
one codecov/shared/
one codecov/gazebo/
one codecov/self-hosted/
one codecov/relay/
one codecov/worker/
```

**Comment by tnt-sentry** [comment]
@chadwhitacre I approved all the Codecov PRs

**Comment by chadwhitacre** [comment]
Thanks @trent-codecov, merged! 😎
