### ISSUE TITLE
Make the case to restate ubiquity

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#236]
Self-hosted is a component of Sentry's ubiquity metric (the "90k orgs" stat we put on all of our [job descriptions](https://sentry.io/careers/#openings), for example). With https://github.com/getsentry/sentry/pull/62441 we now have [quite a different picture🔒](https://docs.google.com/spreadsheets/d/1gHqXan-4dSP1rSyQnSoOiiMGRCC-rgSMTByMCYOuZ4o/edit?usp=sharing) for self-hosted.

We are already using this new understanding in OSPO (e.g., https://github.com/getsentry/team-ospo/issues/232). This ticket is to track working with Sentry's Biz Ops team to update our overall company understanding for reporting. The task is to:

- [ ] redo the work I did to produce the above charts
  - [ ] export [this explore🔒](https://sentryio.cloud.looker.com/explore/super_big_facts/open_source_instances?qid=456UZ4g0FRZZ76Mi4iuCzs&origin_space=211&toggle=vis) from [217🔒](https://sentryio.cloud.looker.com/dashboards/217)
  - [ ] modify the explore to reflect the old state and export that
  - [ ] for both old and new, aggregate versions locally with a script (or figure out how to do it in Looker)
- [ ] document it better (I scrapped the aggregation script I used :sob:)
- [ ] incorporate a ratio of active to inactive installs from the cohort where we have that data to adjust where we don't.

**Comment by hubertdeng123** [comment]
So are we essentially trying to find the ratio of inactive to active installs from 24.1.0+ to try and estimate the amount of active installs we have in the versions 20.0 to 23.12.0, where we don't have that data?

**Comment by hubertdeng123** [comment]
Yep, we do have the info for active vs inactive in the older versions too. Good call

**Comment by chadwhitacre** [comment]
Hehe. ;-)

Yes, we've always known that reported instances is a lower bound, that's still very much true. It's quite eye-opening to me to realize that our self-hosted community is much larger and alive than we previously could see easily. Worth investing in! :-)

**Comment by chadwhitacre** [comment]
Lost momentum on this, gonna close it out for hygiene.
