### ISSUE TITLE
Clean up flakey CI

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#242]
Self-hosted CI has historically been pretty flakey, to the point that we turned it off in `sentry`, `getsentry`, `snuba` for probably a year now.  Unsurprisingly, bugs have snuck into `self-hosted` as a result. Before we can propose to the wider org that we turn self-hosted CI back on, we need to bring CI flakiness under control.

[CI Flakes issues](https://github.com/getsentry/self-hosted/issues?q=is%3Aopen+label%3A%22Type%3A+CI+Flakiness%22+sort%3Acomments-desc)

### PRs

- [x] https://github.com/getsentry/self-hosted/pull/2858
- [x] https://github.com/getsentry/self-hosted/pull/2892
- [x] https://github.com/getsentry/self-hosted/pull/2907
- [x] https://github.com/getsentry/self-hosted/pull/2918
- [x] Resolve https://sentry.sentry.io/issues/5093043103/
- [x] https://github.com/getsentry/self-hosted/pull/2966

**Comment by chadwhitacre** [comment]
Larger goal with this is to be a good citizen of Sentry EPD, so we want to not just fix the five flakes we have but have a fairly robust system for noticing when a test starts to flake and have Sentry monitoring on how often flakes occur.

**Comment by chadwhitacre** [comment]
First task seems to be a "flake flagger" ... some script that runs after test to inspect failure and do a grep to see if any of the flake strings show up in the error output, if so report to Sentry. Then we can root cause and fix based on priority, catch regressions in future, and add new flakes in future.

Will need to repeatedly run tests locally and in CI to trigger flakes.

**Comment by BYK** [comment]
>First task seems to be a "flake flagger" ... some script that runs after test to inspect failure and do a grep to see if any of the flake strings show up in the error output, if so report to Sentry.

The way Sentry detects flakes in `pytest` is try to re-run the test and flag it as flaky if it passes. There seems to be projects allowing retrying GitHub Actions: https://stackoverflow.com/a/71583518/90297

**Comment by chadwhitacre** [comment]
Added a couple punchlist items to the todo and closed [old flake issues](https://github.com/getsentry/self-hosted/issues?q=label%3A%22Type%3A+CI+Flakiness%22) now that we have an automated system for catching them (any still real should resurface there).
