### ISSUE TITLE
Set up $75k drips on GHS from three orgs (`getsentry`, `codecov`, `syntaxfm`).

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#247]

**Comment by chadwhitacre** [comment]
Syntax is done. Need to do codecov and getsentry. It's complicated by the fact that we already have sponsorships set up in those orgs.

**Comment by chadwhitacre** [comment]
I can't cancel through the bulk recurring UI.

**Comment by chadwhitacre** [comment]
And I can't update through the bulk recurring UI. If there's already a sponsorship I get an error.

**Comment by chadwhitacre** [comment]
If I can cancel all existing sponsorhips through the GraphQL API, will I be able to use the new bulk UI to set up new ones?

**Comment by chadwhitacre** [comment]
No. A pending cancellation prevents creating a new sponsorship. 🤔

![Image](https://github.com/user-attachments/assets/371af173-fce2-407a-83e2-44a14d95f356)

**Comment by chadwhitacre** [comment]
I see a "Cancel sponsorship" option on some maintainers but not others. Even so, it schedules the cancellation, it's not immediate.

![Image](https://github.com/user-attachments/assets/618fdd95-9c58-4eaf-9919-a7b3c4f147eb)

![Image](https://github.com/user-attachments/assets/a4777033-406e-4e05-9e1d-1bb3b781f897)

**Comment by chadwhitacre** [comment]
Eureka! Disabling sponsors for the org at the enterprise level has the effect of canceling all current sponsorships. 💃

**Comment by chadwhitacre** [comment]
Dialing back out to #163.

**Comment by BYK** [comment]
>Disabling sponsors for the org at the enterprise level has the effect of canceling all current sponsorships. 💃

This combined with what you reported earlier makes me sad (due to inconsistency and how hard this became) 😅

**Comment by chadwhitacre** [comment]
It is super hard, the tooling across all platforms has a lot of room for improvement. We'll get there!
