### ISSUE TITLE
Tighten up Discussions in getsentry/sentry

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#32]
We have a good [process](https://open.sentry.io/triage/) for staying on top of GitHub Issues, but we're not staying on top of [Discussions in `getsentry/sentry`](https://github.com/getsentry/sentry/discussions) (just like we were never really on top of the [forums](https://forum.sentry.io/)).

We should look at the types of traffic that come through and figure out a process for handling it to avoid [bad customer experience](https://twitter.com/dave_stewart/status/1551541075810164739).

### To Do

- [x] audit existing threads in getsentry/sentry
- [x] figure out process for support requests
- [x] figure out plan for product conversations
- [x] [audit discussions across all repos](https://docs.google.com/spreadsheets/d/1yk8dCi2d3GTdZVydq8FXzg156PYhqxDb04sMla8IyC4/edit?pli=1#gid=0)
- [x] process non-self-hosted support requests
- [x] process self-hosted support requests

**Comment by chadwhitacre** [comment]
# Audit

## Product Spitballin'

### Us

https://github.com/getsentry/sentry/discussions/36492
https://github.com/getsentry/sentry/discussions/34970
https://github.com/getsentry/sentry/discussions/34968
https://github.com/getsentry/sentry/discussions/34590
https://github.com/getsentry/sentry/discussions/34971

### Them

https://github.com/getsentry/sentry/discussions/35821
https://github.com/getsentry/sentry/discussions/35134
https://github.com/getsentry/sentry/discussions/34686

## Questions, Gnawing Questions

### JavaScript

https://github.com/getsentry/sentry/discussions/36981
https://github.com/getsentry/sentry/discussions/36914

### Some SDK

https://github.com/getsentry/sentry/discussions/36905

### self-hosted

### Bug

https://github.com/getsentry/sentry/discussions/35424

**Comment by chadwhitacre** [comment]
Had a bunch of internal conversations about this. The tl;dr is that we either need to:

1. Allocate resources to support customers in public GitHub (not just feature requests and bug reports but customer support requests).
2. Significantly scale back our Discussions and possibly Discord channels to avoid setting expectations we can't keep.

**Comment by vladanpaunovic** [comment]
Thanks @chadwhitacre!

I did a similar breakdown of discussions in `getsentry/sentry-javascript` a while ago and it boiled down to this two approaches that you mentioned.

I think it is reasonable to exclude Discord from this conversation as it is a different problem to solve and I have seen that as of recently, our DevRel team started engaging way more there which I see as a step in a right direction.


Here are my thoughts: 
> 1. Allocate resources to support customers in public GitHub (not just feature requests and bug reports but customer support requests).

This is a reasonable ask and a desirable outcome in my opinion. In other words: support doing support, DevRel doing DevRel. Engineering will help where necessary. 

> 2. Significantly scale back our Discussions and possibly Discord channels to avoid setting expectations we can't keep.

This has implications on engineering teams and objectives as then `engineering = (support + DevRel)` (which is the case at the moment and results in us switching context much more time in a day than we would like to + keeping track on our priorities is a suffering). 
All we are doing then is pushing all this work to engineering exclusively, leaving them less time to actually do engineering. In my opinion, not optimal.


Also, this would probably imply that `discussions = issues`. The result here is that engineering will inherit an SLO that essentially does not belong to them which I am opposed to.

**Comment by chadwhitacre** [comment]
Audit across repos:

<img width="979" alt="Screen Shot 2022-08-02 at 3 00 24 PM" src="https://user-images.githubusercontent.com/134455/182452870-2041777f-cbdc-4b2c-aa14-3df3318e43c3.png">

**Comment by chadwhitacre** [comment]
Ooooh ... copy/paste from Sheets Just Works™️. 😍 


Repository | Link | Number of Discussions
-- | -- | --
sentry | https://github.com/getsentry/sentry/discussions | 84
sentry-javascript | https://github.com/getsentry/sentry-javascript/discussions | 54
sentry-dotnet | https://github.com/getsentry/sentry-dotnet/discussions | 19
sentry-cocoa | https://github.com/getsentry/sentry-cocoa/discussions | 9
sentry-dart | https://github.com/getsentry/sentry-dart/discussions | 9
sentry-java | https://github.com/getsentry/sentry-java/discussions | 7
sentry-php | https://github.com/getsentry/sentry-php/discussions | 6
sentry-react-native | https://github.com/getsentry/sentry-react-native/discussions | 4
sentry-symfony | https://github.com/getsentry/sentry-symfony/discussions | 4
sentry-go | https://github.com/getsentry/sentry-go/discussions | 4
sentry-unity | https://github.com/getsentry/sentry-unity/discussions | 3
sentry-python | https://github.com/getsentry/sentry-python/discussions | 2
sentry-laravel | https://github.com/getsentry/sentry-laravel/discussions | 2
sentry-capacitor | https://github.com/getsentry/sentry-capacitor/discussions | 2
sentry-unreal | https://github.com/getsentry/sentry-unreal/discussions | 1
sentry-android-gradle-plugin | https://github.com/getsentry/sentry-android-gradle-plugin/discussions | 0
action-github-app-token | https://github.com/getsentry/action-github-app-token/discussions | 0

**Comment by chadwhitacre** [comment]
Calling this good. There's a bit of an open question about SDKs. For now:

1. SDKs can do what they want with issues vs. discussions.
2. Tentatively thinking of Discussions as being for customer support requests using an answerable category. Relatively easy to convert an issue to a discussion (much clunkier the other way).
3. Will continue to support Support in our weekly meetings this month to engage on [Discussions in the support repo](https://github.com/getsentry/support/discussions).
4. Will revisit at our Support monthly to see how it's going, solidify commitment to Discussions at that point (or not) and revisit SDKs.
