### ISSUE TITLE
More regular reminders for issues that need triaging

### ISSUE THREAD

**Issue by armenzg** [getsentry/team-ospo#41]
### Requirements

1. Buckets:
    1. overdue = overdue
    1. act fast = less than 4 hours to deadline (or deadline is after end of day)
    1. triage queue = remaining tickets
1. Check queue once per hour.
    1. This is in addition to the immediate notification when a new ticket comes in.
1. If any are overdue or in act fast, post.
1. If we haven't posted in four hours, post.
1. Message format:

> Hey! You have some tickets to triage:
>
> 🚨 **Overdue** 😰
> - "[$github_issue_title]<linked>" 8 hours overdue
> - "[$github_issue_title]<linked>" 2 hours overdue
> - "[$github_issue_title]<linked>" 1 hour overdue
>
> ⌛️ **Act fast!** 😨
> - "[$github_issue_title]<linked>" 15 minutes left
>
> ⏳ **Triage Queue** 😯
> - "[$github_issue_title]<linked>" 8 hours left
> - "[$github_issue_title]<linked>" 24 hours left
> - "[$github_issue_title]<linked>" 22 hours left
> - "[$github_issue_title]<linked>" 36 hours left
> - "[$github_issue_title]<linked>" 48 hours left 👈 quick win?

# Original

The workflow team receives Issue pending alerts in Slack, however, if an alert is missed we will not hear about it anymore.

For instance, [this issue](https://github.com/getsentry/sentry/issues/37674) was not triaged and I got pinged on Slack yesterday (9 days after the issue was tagged for triaged)

We should get reminded every day until we triage the queue.

Thanks!

<img width="589" alt="image" src="https://user-images.githubusercontent.com/44410/190161769-624c5dda-4303-4e3b-b75b-ac0615da6156.png">

<img width="842" alt="image" src="https://user-images.githubusercontent.com/44410/190161580-82e248e1-6bd5-48d4-8c67-4420bec81ce6.png">

### To Do

- [x] backfill offices for channels with existing triaging rules
- [x] https://github.com/getsentry/eng-pipes/pull/376
- [x] https://github.com/getsentry/ops/pull/5857
- [x] https://github.com/getsentry/eng-pipes/pull/377
- [x] https://github.com/getsentry/ops/pull/5863
- [x] https://github.com/getsentry/eng-pipes/pull/381

**Comment by chadwhitacre** [comment]
Thanks @armenzg, I thought we had something for this (at least for issues over triage) but I can't find it now. I agree this would be better than current process which involves human review on a weekly cycle, expensive and slow.

**Comment by BYK** [comment]
It is pinging an open endpoint on eng-pipes so you can probably change the logic there.

**Comment by chadwhitacre** [comment]
> the scheduled job trigger is GCP

Oooooooh! Thanks @BYK! 😅
