### ISSUE TITLE
Upgrade prod automatically

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#44]
### Problem Statement

We want to keep our dogfood instance on GCP up to date with the self-hosted master branch

### Solution Brainstorm

pipeline to run `./install.sh` after pushing to master?

**Comment by BYK** [comment]
>pipeline to run ./install.sh after pushing to master?

`./install.sh --minimize-downtime` would probably be better but I remember that not working very reliably from @scefali

**Comment by ethanhs** [comment]
I am currently thinking updating daily will be sufficient and much easier to implement, just a cron job on the self-hosted prod instance.

> ./install.sh --minimize-downtime would probably be better but I remember that not working very reliably

@BYK do you mean that it would error out or not reliably minimize downtime?

I am going to look at the timestamps of when the events we have received so far are from and see if there is a lull which would be a good time to update.

**Comment by BYK** [comment]
>@BYK do you mean that it would error out or not reliably minimize downtime?

If I remember correctly it may leave `relay` in a non-functional state due to some stupid DNS issue inherent in Docker Compose. Maybe v2+ resolved those so YMMV

**Comment by ethanhs** [comment]
This is now running daily on a cron.
