### ISSUE TITLE
Send full log as attachment to event

### ISSUE THREAD

**Issue by ethanhs** [getsentry/team-ospo#46]
We currently only get the last 100 lines of logs as a breadcrumb. Ideally we want to send the full thing as an attachment.

**Comment by ethanhs** [comment]
I have put a branch with a WIP implementation: https://github.com/getsentry/self-hosted/tree/ethanhs/attach-logs. That branch currently has 2 issues:

1) the size of the log is counted incorrectly by `wc -c`, which I am guessing is some issue with Unicode taking multiple bytes? (the size difference between Python's calculation and `wc -c` is constant for different logs)
2) Even after correctly calculating the size, and successfully dispatching an envelope with the log, it does not show up in the prod instance, and there are no logs indicating an issue in processing the envelope that I could find.

**Comment by hubertdeng123** [comment]
I was able to create an event with an attachment, example here:

https://self-hosted.getsentry.net/organizations/self-hosted/issues/52/events/7eccc7d914ae4ff0beabbdc4181689c0/?project=3&statsPeriod=14d

Sample envelope:
```
{"event_id":"12c2d058d58442709aa2eca08bf20986","dsn": "https://19555c489ded4769978daae92f2346ca@self-hosted.getsentry.net/3"}
{"type":"event","length":41,"content_type":"application/json"}
{"message":"hello world","level":"error"}
{"type":"attachment","length":7,"content_type":"text/plain","filename":"log.txt"}
Content

```
