### ISSUE TITLE
Security Sync on Dogfood Instance

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#48]
Sync with security team to ensure we aren't leaving ourselves vulnerable to anything obvious

- [x] GCP account for dogfooding should have a specific service account associated with it
- [x] Move dogfood VM to IAP + OSLogin
- [x] Matt has requested access to our self-hosted project and will poke around to see if there's anything else

**Comment by hubertdeng123** [comment]
1. GCP account for dogfooding should have a specific service account associated with it
2. move dogfood VM to IAP + OSLogin

**Comment by chadwhitacre** [comment]
Did Matt turn up anything else? Are we ticketing that separately? Or ... ?

**Comment by hubertdeng123** [comment]
He didn't turn up anything else after looking. If there's additional items I'll ticket that separately as those should not block dogfooding
