### ISSUE TITLE
Properly set up self-hosted dogfooding email with the domain

### ISSUE THREAD

**Issue by ethanhs** [getsentry/team-ospo#50]
Our prod instance is was set up before we had a domain, so we need to set up the email server to use the correct domain such that we don't send emails as `sentry@localhost`, which Google (and I'm sure other email providers) find very suspicious.

**Comment by ethanhs** [comment]
This has been done, now comes from self-hosted.getsentry.net!

**Comment by chadwhitacre** [comment]
Yesssssssssssss. 👍

Anything worth noting in our [docs](https://www.notion.so/sentry/Sentry-Dogfood-Instance-8e66968558a14a47a704a38ae5532963)?

**Comment by ethanhs** [comment]
Not really, its the bog standard changes as documented!
