### ISSUE TITLE
Publish the Vroom repo

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#51]
From @jernejstrasner in private Slack:

> Let’s make vroom open source! How do we get it done properly? Licenses and all.

https://github.com/getsentry/vroom

## To Do

- [x] https://github.com/getsentry/vroom/pull/94
- [x] Run https://github.com/trufflesecurity/trufflehog on repo _history_ (already have on new PRs or something?).
- [x] Deal with any secrets discovered, either by removing them from history or rolling them.
- [x] [Have security sign off.🔒](https://getsentry.atlassian.net/browse/INFO-1) - also https://github.com/getsentry/vroom/issues/165
- [x] Do a GitHub dance.

**Comment by BYK** [comment]
Is it something like this: 🚗 💨

**Comment by chadwhitacre** [comment]
This is the backend for profiling. 😃

**Comment by chadwhitacre** [comment]
Process is:

1. Run https://github.com/trufflesecurity/trufflehog on repo.
2. Deal with any secrets discovered, either by removing them from history or rolling them.
3. Add a LICENSE file w/ BSL.
4. Publish! :)

**Comment by chadwhitacre** [comment]
BSL confirmed with Legal.

**Comment by chadwhitacre** [comment]
Process vetted by Security. 👍

**Comment by chadwhitacre** [comment]
Change date will come with https://github.com/getsentry/self-hosted/issues/1838. Fine to have a fixed far future date to start.

**Comment by mdtro** [comment]
@chadwhitacre - do you have access to give the security team at least write access to the repo? 🙂 I'd like to make a PR to get Dependabot configured on it.

**Comment by chadwhitacre** [comment]
Yup, done. :)

**Comment by chadwhitacre** [comment]
Congrats! :)
