### ISSUE TITLE
Make email warning from getsentry prod go away

### ISSUE THREAD

**Issue by ethanhs** [getsentry/team-ospo#52]
Currently if you look up our VM's IP it points to a `googleusercontent.com` domain. We want it to point to `self-hosted.getsentry.net`.

**Comment by chadwhitacre** [comment]
Are you sure this is the only thing causing the warnings in Gmail? What about SPF and DKIM?

**Comment by chadwhitacre** [comment]
I'd like to see us scope this ticket to "Make the warnings go away" (outcome) not just "set up reverse DNS" (output).

<img width="952" alt="Screen Shot 2022-10-17 at 12 09 34 PM" src="https://user-images.githubusercontent.com/134455/196228187-d77835b3-c164-46cf-bf91-a3ea1e00f8ac.png">

**Comment by ethanhs** [comment]
<img width="1162" alt="Screen Shot 2022-11-04 at 9 21 53 AM" src="https://user-images.githubusercontent.com/9504279/200025892-09a58419-88aa-4dfb-9a22-0a0066cf141e.png">

Success!
