### ISSUE TITLE
Cleanup teams and labels and docs

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#60]
- [ ] Figure out what changes we want to make.
- [ ] Update https://open.sentry.io/structure/.
- [ ] Update [Open Source Support - Structure w/ Slack Channels](https://www.notion.so/sentry/Open-Source-Support-Structure-w-Slack-Channels-eeb53976e3014e498e32d2beee922dd7).
- [ ] Update [Product and Service Registry](https://www.notion.so/Product-and-Service-Registry-f90c702816794dcaa7f81ef8e79e40ea) (likely big deal, coordinate with whoever owns this in EPD).
- [ ] Migrate labels.

**Comment by chadwhitacre** [comment]
lol dogs?

**Comment by hubertdeng123** [comment]
docs woops

**Comment by chadwhitacre** [comment]
Not having a good source of truth here adds friction to routing and triage.

Support made their own notion doc to map teams to Slack channels to aid in routing.

We were sending tickets to Core UI and does that team even exist anymore? Conflicting answers.

**Comment by chadwhitacre** [comment]
Closing in favor of #90.
