### ISSUE TITLE
Compute business day notifications with more granularity in routing/triage logic

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#62]
We have routing and triage SLOs of 1 business day and 2 business days, but we have a pretty rough computation of what constitutes a "business day" right now. Let's [provide well-timed notifications](https://github.com/getsentry/team-ospo/issues/41) and also more accurate stats in the dashboard. This can be done by using our office hours to compute more specific business hours for our notifications.

- [x] #67
- [x] https://github.com/getsentry/eng-pipes/pull/353
- [x] https://github.com/getsentry/team-ospo/issues/69
- [x] https://github.com/getsentry/eng-pipes/pull/365
- [x] https://github.com/getsentry/lookml/pull/497

**Comment by hubertdeng123** [comment]
Notes:

1. add timeToTriageBy, timeToRouteBy columns in db
2. logic for determining non business days lives in eng-pipes
3. use google cloud scheduler for hourly checkup on issues

**Comment by hubertdeng123** [comment]
## Weekly update Nov 14:

- `/notify-for-triage` with office arg has been merged
- brainstorming of how notifications will be set up mostly ironed out (will use BigQuery to store the timeToTriageBy and timeToRouteBy timestamps, weekend/business day logic will be set up in eng pipes entirely)
- draft PR up for moving weekend logic to eng-pipes

**Comment by chadwhitacre** [comment]
Sketch of what's needed for this:

1. When an issue is routed, i.e., a new `Team: *` label is applied, we field the GH event and we have an issue number and a team slug/identifier. We need to compute the business hours for the team in question.
2. Business hours are a property of channel subscriptions. Teams to channels are N:M.
3. ~~We could try storing a team:business hours mapping that gets updated every time we get a subscription change.~~
4. We could also compute business hours for the team by looping over channels. We don't get that many tickets and we don't have that many teams, this shouldn't be expensive.
5. We set `timeTo{Route,Triage}By` based on the composite business hours of all channels.
6. We notifying channels base on their individual business hours per their office subscriptions.

![IMG_1378](https://user-images.githubusercontent.com/134455/204396800-8e599762-f08c-498a-9f70-e0589fc69a85.JPG)
