### ISSUE TITLE
Set up GitHub ⇔ Jira connector

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#63]
To support https://github.com/getsentry/team-ospo/issues/42 we want to set up an automation that creates a shadow Jira ticket for issues in the `sentry` GitHub repo. The purpose of the Jira ticket is to integrate with our existing customer tagging/[tracking](https://getsentry.atlassian.net/jira/software/c/projects/ISSUE/boards/25) infrastructure, as well as our sprints and planning for EPD. Most comments and content should stay on GitHub. Ideally we wouldn't create a Jira for _every_ GitHub, but only when we want to start doing something with it in Jira (tag a customer, bring it into a sprint, etc.(?)).

### Requirements

1. When someone applies `Trigger: Create Jira Ticket`
    1. Check the description for a link to an existing Jira.
    2. Create a new Jira if it doesn't exist, and link it in the description.
    3. Remove `Trigger: Create Jira Ticket`
1. When resolved in Jira.
    1. Close on GitHub.
1. When unresolved in Jira.
    1. Reopen on GitHub.

### To Do

- [x] Evaluate options, integration vendors vs. diy with eng-pipes.
- [x] Pin down requirements.
- [x] Investigate Unito a little more.
    - [x] Understand permissions.
    - [x] Try to guess how it will break for us.
    - [x] Pin down pricing.
    - [x] Have a call with Unito.
- [x] Submit [SaaS intake](https://docs.google.com/forms/d/e/1FAIpQLSdRP-zaqelk0dSg8BV-OIGaW9WnXPF9AVQPWSZgQPdtxcg-tQ/viewform).
- [x] Go through legal / security review.
- [x] Buy Unito.
- [x] Do a little label maintenance.
    - [x] https://github.com/getsentry/sentry/pull/42447
    - [x] https://github.com/getsentry/sentry/pull/42452
        - This is a sidebar, but I'm thinking of Trigger and Sync as cousins and want to use the same color.
- [x] Configure Unito in `sentry`.
    - [x] [Install Unito on GitHub.](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-3993)
    - [x] [Install Unito on Jira.](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-3962)
    - [x] ~Put the thing in Advanced Options to avoid status jump on unlabel.~
- [ ] Add to remaining repos.
    - [x] self-hosted
    - [x] sentry-docs
    - [x] relay
    - [x] sentry-javascript
    - [x] sentry-php
    - [x] sentry-python
    - [x] sentry-react-native
    - [x] sentry-laravel
    - [x] sentry-cocoa
    - [x] sentry-dart
    - [x] sentry-dotnet
    - [x] sentry-java
    - [x] sentry-native
    - [x] sentry-ruby
    - [x] sentry-symfony
    - [x] sentry-unity
    - [x] sentry-android-gradle-plugin

**Comment by BYK** [comment]
Sounds like you may wanna try [Pipedream](https://pipedream.com) out.

**Comment by chadwhitacre** [comment]
Yeah, maybe! I saw when you first linked that a while ago (probs on Twitter?). Are you actively using it?

**Comment by chadwhitacre** [comment]
Options:

- Pipedream
- Zapier
- eng-pipes
- ???

**Comment by BYK** [comment]
@chadwhitacre we've been using it at Formsort for many things and it works quite well. I think for Sentry's scale, you'd need to pay for the pro/team account up front as the daily limit of 66 invocations is a bit too low. The individual dev plan has more headroom for initial testing though.

We did build out that magical "automated changelog based on SaaS deploys powered by Jira tickets" thing we have been thinking about :)

**Comment by chadwhitacre** [comment]
Why should we use a nocode solution instead of eng-pipes?

**Comment by BYK** [comment]
It is not a no-code solution. You do write code but don't have to deal with the boring and error-prone parts like authentication, tokens etc. Arguably, you can probably replace whole eng-pipes with Pipedream workflows.

**Comment by chadwhitacre** [comment]
Link dump:

https://exalate.com/ppc-jira-github-integration/
https://marketplace.atlassian.com/apps/1218053/github-jira-two-way-sync
https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/

**Comment by chadwhitacre** [comment]
https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/ - doesn't apply, it only covers code on GitHub not issues

https://exalate.com/ppc-jira-github-integration/

https://marketplace.atlassian.com/apps/1218053/github-jira-two-way-sync => https://unito.io/integrations/jira-github/, I started looking at this a long time ago.

So that's [Exalate](https://exalate.com/blog/jira-github-integration/) and [Unito](https://unito.io/integrations/jira-github/) in addition to [Pipedream](https://pipedream.com/apps/jira/integrations/github) and [Zapier](https://zapier.com/apps/github/integrations/jira).

**Comment by chadwhitacre** [comment]
#### Twitter Followers

| Company | n |
|:---|---:|
| [Zapier](https://twitter.com/zapier) | 70,253 |
| [Pipedream](https://twitter.com/pipedream) | 6,524 |
| [Unito](https://twitter.com/unitoio) | 1,067 |
| [Exalate](https://twitter.com/exalatetool) | 21 |

I [checked](https://www.notion.so/Software-1913565c0c5847acb855eaabbabee827), we don't already have any of these.

**Comment by chadwhitacre** [comment]
No-one ever got fired for buying Zapier? :o)

**Comment by chadwhitacre** [comment]
There's a "New Label in GitHub" event in Zapier but not afaict an "Apply label to issue" event.

**Comment by chadwhitacre** [comment]
Same with Pipedream, but there is a "create it" option.

<img width="918" alt="Screen Shot 2022-11-11 at 12 10 49 PM" src="https://user-images.githubusercontent.com/134455/201393291-bf36f222-a76f-44cc-8d17-1b13247e799e.png">

**Comment by chadwhitacre** [comment]
I looked through Pipedream's issues and PRs and didn't see anything already in the works for this event.

**Comment by BYK** [comment]
@chadwhitacre I think you are looking for "New or Updated Issue (Instant)"?

**Comment by chadwhitacre** [comment]
Afaict Zapier and Pipedream are focused on one-way automations, vs. Unito and Exalate which are focused on bidirectional syncing between objects in disparate systems.

**Comment by chadwhitacre** [comment]
Unito was super easy to set up, no code! 😁

https://github.com/org-3392dc2e/testing/issues/1

**Comment by chadwhitacre** [comment]
<img width="1310" alt="1" src="https://user-images.githubusercontent.com/134455/201984477-28fc68d4-51e6-4409-91c5-f65c4e811c43.png">

<img width="1310" alt="2" src="https://user-images.githubusercontent.com/134455/201984475-987f1be4-0ac7-4d2e-9c80-c2060415ae0f.png">

<img width="1310" alt="3" src="https://user-images.githubusercontent.com/134455/201984474-15c663ec-5fe5-48d9-a2b2-3f0d086ac79a.png">

<img width="1310" alt="4" src="https://user-images.githubusercontent.com/134455/201984471-e107ce38-5127-478a-a572-f89ed970a159.png">

<img width="1310" alt="5" src="https://user-images.githubusercontent.com/134455/201984470-ff432137-8269-41b4-9996-c5248707e82d.png">

**Comment by chadwhitacre** [comment]
Seeing an unexpected result, when I remove the label from [the GitHub issue](https://github.com/org-3392dc2e/testing/issues/1), it moves [the Jira ticket](https://chadwhitacre.atlassian.net/jira/software/projects/TEST/boards/1?selectedIssue=TEST-1) to "Done" and vice versa.

<img width="499" alt="Screen Shot 2022-11-15 at 2 26 18 PM" src="https://user-images.githubusercontent.com/134455/202007955-21e53543-a1ff-49db-91e1-d09ee2c3a0cf.png">

**Comment by chadwhitacre** [comment]
Looking into Unito/Jira auth ...

https://guide.unito.io/a-guide-to-unitos-jira-integration
https://guide.unito.io/what-permissions-are-required-for-jira-users

**Comment by chadwhitacre** [comment]
Unito GitHub perms FTR ...

https://guide.unito.io/what-permissions-are-required-for-github-users

**Comment by chadwhitacre** [comment]
> **Note**: Before setting up permissions, we recommended you [create a Jira bot user](https://2694792.hs-sites.com/knowledge/how-to-create-a-bot-user-in-unito).

Well there ya go. :) That's for Jira.

**Comment by chadwhitacre** [comment]
# Pricing

👉 **https://unito.io/pricing/** 👈

The word from GTM is that this would be useful across all [tier 1 repos](https://open.sentry.io/structure/). That's currently [2,210 open issues/PRs](https://github.com/search?q=is%3Aissue+is%3Aopen+repo%3Agetsentry%2Fsentry+repo%3Agetsentry%2Fself-hosted+repo%3Agetsentry%2Fsentry-docs+repo%3Agetsentry%2Frelay+repo%3Agetsentry%2Fsnuba+repo%3Agetsentry%2Fsnuba-sdk+repo%3Agetsentry%2Fsentry-javascript+repo%3Agetsentry%2Fsentry-php+repo%3Agetsentry%2Fsentry-python+repo%3Agetsentry%2Fsentry-react-native+repo%3Agetsentry%2Fsentry-laravel+repo%3Agetsentry%2Fsentry-cocoa+repo%3Agetsentry%2Fsentry-dart+repo%3Agetsentry%2Fsentry-dotnet+repo%3Agetsentry%2Fsentry-java+repo%3Agetsentry%2Fsentry-native+repo%3Agetsentry%2Fsentry-ruby+repo%3Agetsentry%2Fsentry-symfony+repo%3Agetsentry%2Fsentry-unity+repo%3Agetsentry%2Fsentry-android-gradle-plugin+repo%3Agetsentry%2Fresponses+repo%3Agetsentry%2Fsymbolic+repo%3Agetsentry%2Fsymbolicator+repo%3Agetsentry%2Fcraft+repo%3Agetsentry%2Farroyo+repo%3Agetsentry%2Fcdc+repo%3Agetsentry%2Fwal2json&type=issues).

Unito prices are based on "[items in sync](https://guide.unito.io/what-are-items-in-sync)," and each side counts for one, so if all 2,210 issues are synced from GitHub to Jira then that is 4,420 items. I don't expect all tickets will have a Jira shadow, certainly not off the bat. That said we are likely to see more tickets created in GitHub more rapidly than before. Some [history](https://www.notion.so/sentry/What-happened-to-GitHub-7979d50330ea4f70b570c608a6931b2c):

![](https://user-images.githubusercontent.com/134455/202303098-3afaf238-9903-4797-85df-4c7fe0e19312.png)

### Assumptions

1. We will be able to define "items in sync" as open GitHub issues with `Sync: Jira` label applied, across 27 repos.
2. Eyeballing on the above chart:
    - 3,600 total new in `getsentry` in 2019
    - 6,000 in 2020 / 3,600 = 1.67
    - 7,200 in 2021 / 6,000 = 1.2
    - 9,000 in 2022 / 7,200 = 1.25
 3. So that is 1.2x – 1.67x growth yoy in `getsentry` repo. Let's assume roughly the same rate in other repos.
 4. How many issues will have the `Sync: Jira` label applied? 10%? 50%? 80%?

### Scenarios

- _lo_ - 10% labeled, 1.2x growth
- _mid_ - 50% labeled, 1.4x growth
- _hi_ - 80% labeled, 1.7x growth

Base is 4,420, calculation is "items in sync".

| scenario | now | now + 1yr | now + 2 yrs | now + 3 yrs |
|:---|---:|---:|---:|---:|
| *lo* | 442 | 530 | 637 | 764 |
| *mid* | 2,210 | 3,094 | 4,331 | 6,064 | 
| *hi* | 3,536 | 6,011 | 10,219 | 17,372 |

I'm inclined to lean towards the higher estimate, because the whole point of this exercise is to get more issues created in GitHub, both by GTM teams and by customers directly. On the other hand it's not like we're going to label 3,500 issues immediately out of the gate. We'll start with zero, maybe label a couple hundred in an initial migration, and then grow from there.

## Plans

The two relevant plans are:

| Plan | Items | $/yr | Sync Lag |
|:----|:----|:---|:----|
| Team | 150 – 2,000 | 288 – 1,668 | ~6 minutes |
| Company | 1,500 – 15,000 | 2,376 – 11,700 | ~20 seconds |


## Conclusion

I think we should go for the low end of the Company plan. We don't know exactly what to expect but if we're successful we should see significant growth this year. Remember that every new labeled GitHub issue counts for two items in sync, so we only need to label/sync 1,000 of our existing 2,210 issues (let alone sync _new_ issues) in order to max out the Team plan. The sub-minute lag time will be beneficial for maintaining flow state for the ICs creating tickets.

**Comment by chadwhitacre** [comment]
Had a call w/ sales, open questions:

1. Is it expected behavior to change status in Jira when the label is removed/re-applied? If so, is there a workaround to prevent the Jira change?
2. Are checkbox tasks in GitHub indeed considered "items in sync," or only if/when converted to issues?

**Comment by chadwhitacre** [comment]
> Is it expected behavior to change status in Jira when the label is removed/re-applied?

Maaaaaybe?

> If so, is there a workaround to prevent the Jira change?

They're offering a manual workaround once we have the prod flow ready.

> Are checkbox tasks in GitHub indeed considered "items in sync"?

No.

**Comment by chadwhitacre** [comment]
One limitation with Unito is that we can't sync items after they've already been created. The workflow would hav to be to recreate in GitHub and then go from ther.e

**Comment by chadwhitacre** [comment]
I clobbered the footer in both GH and Jira for https://github.com/org-3392dc2e/testing/issues/5 and found that the connection appears to survive. Pure gravy.

**Comment by chadwhitacre** [comment]
Working through negotiations with Unito now, making progress.

**Comment by chadwhitacre** [comment]
NDA signed, proceeding with Security review.

**Comment by chadwhitacre** [comment]
Hrm, Security questions.

Other bidirectional sync vendors:

https://getint.io/ 
~~https://www.appseconnect.com/~~ - [whack pricing](https://www.appseconnect.com/pricing/)
exalate

Meh blah nerp:

https://www.workato.com/how_it_works similar Zapier
https://www.connectall.com/ blah

**Comment by chadwhitacre** [comment]
Compliance passed! Now to purchase and configure ...

**Comment by chadwhitacre** [comment]
Purchased. Installed in GitHub. Need help with Jira.

**Comment by chadwhitacre** [comment]
Got help with Jira!

<img width="926" src="https://user-images.githubusercontent.com/134455/208095044-21e251d2-778d-4933-a21a-5ff35ec0dd53.png">

**Comment by chadwhitacre** [comment]
Installed for `sentry`! 💃

**Comment by chadwhitacre** [comment]
> Add to remaining repos.

Punting on this until there is demand. `sentry-javascript` has [a `Jira` label already](https://github.com/getsentry/sentry-javascript/labels?q=jira), will need to coordinate with them on that.

**Comment by chadwhitacre** [comment]
> Put the thing in Advanced Options to avoid status jump on unlabel.

Punting. Shouldn't be common.

**Comment by chadwhitacre** [comment]
Dropping getsentry/sentry#42452 from scope here so I can close. 💃

**Comment by chadwhitacre** [comment]
jk reopening to roll out to remaining repos, [first one](https://github.com/getsentry/sentry-dart/issues/1200) was in sentry-dart lol

**Comment by chadwhitacre** [comment]
I've (manually) added the label in all of the [Core and SDK repos](https://open.sentry.io/structure/). I don't think we need this in Shared repos, nobody from GTM should care about those.

**Comment by chadwhitacre** [comment]
I removed the Unito GitHub App from these repos we don't care to track:

1. [snuba](https://github.com/getsentry/snuba)
2. [snuba-sdk](https://github.com/getsentry/snuba-sdk)
3. [responses](https://github.com/getsentry/responses)
4. [symbolic](https://github.com/getsentry/symbolic)
5. [symbolicator](https://github.com/getsentry/symbolicator)
6. [craft](https://github.com/getsentry/craft)
7. [arroyo](https://github.com/getsentry/arroyo)
8. [cdc](https://github.com/getsentry/cdc)
9. [wal2json](https://github.com/getsentry/wal2json)

**Comment by chadwhitacre** [comment]
Confirmed they do care about Relay (makes sense since it's customer-facing).

**Comment by chadwhitacre** [comment]
Done rolling out to other repos.
