### ISSUE TITLE
[Branding] Sentry OSPO Mascot or Insignia

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/team-ospo#70]
### Problem Statement:

Members of the support-open-source team realized that not all of our colleagues at Sentry are aware of our work or affiliation with team-ospo and the open source community.

### Brainstorming:

We thought it might be worth pursuing internally as a team, and with design, some kind of mascot, or insignia that helped signal to our colleagues and the community these additional responsibilities.

#### MOAR Brainstorming

What do you think of when you think of Sentry's open source community? Is it ubiquitous cat-butt? Is it ever-dancing Chad 💃 ?

We've already got ~~sentry-pink Octocat~~ looks like this logo might be offlimits for reasons: 
![image](https://user-images.githubusercontent.com/76002357/201763633-47a3a5eb-03ba-49c7-91e6-b0d77e447693.png)

**Comment by chadwhitacre** [comment]
Oooooh. Where would you see this being used or showing up?

**Comment by BYK** [comment]
We definitely need a purple dancing Chad

**Comment by souredoutlook** [comment]
> We definitely need a purple dancing Chad

Yes.

> Where would you see this being used or showing up?

Something for the team to have in their slack bios (and as a slack emoji) and also in our Slack/GitHub profile pics - something that visually points that out would be helpful in raising awareness.

Might also be helpful for visually identifying our Vanguard/Shipped posts and pinned comments etc.

We'll also be getting the rest of the crew onboard with cartoon headshots just to keep things looking professional and uniform.

**Comment by souredoutlook** [comment]
Leaving this here for when we're ready to 🚀 https://www.notion.so/sentry/How-do-I-get-a-logo-for-my-team-d5c0ab9cee0448eda5d8f41676d8b430

**Comment by chadwhitacre** [comment]
How are we doing on awareness of Support's role w/ GitHub, @souredoutlook? Is this ticket still interesting beyond the obvious appeal of having Creative make a purple dancing Chad? 😁

**Comment by chadwhitacre** [comment]
I think by now the visibility of support's role in open source is higher, I'm going to close this out. <3
