### ISSUE TITLE
Gain access to Discourse

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#78]
I can't login to [Discourse](https://forum.sentry.io/) because it is in read-only mode. The answer [seems to be](https://meta.discourse.org/t/unable-to-login-as-admin-after-enabling-read-only-mode/85362/3) to SSH in and run `rails c`. 😐

We have two issues to resolve:

- [ ] A user has asked to have their account removed.
- [ ] We get these weird fails on direct access to forum links.

Output of this ticket is a doc in Notion (similar to our dogfooding doc) that documents our Discourse setup and how to access it.

**Comment by shanamatthews** [comment]
Hey @chadwhitacre - would it be possible to get this prioritized? Just got a ping from the user on Discord on this.

**Comment by shanamatthews** [comment]
@chadwhitacre - just bringing this one up again ❤️🙏

**Comment by mic4ael** [comment]
Hey! Can I ask if there was any progress on this? :)

**Comment by chadwhitacre** [comment]
I've started an [internal ticket](https://getsentry.atlassian.net/jira/software/c/projects/OPS/boards/101) to try to track this down with our Ops team.

**Comment by mic4ael** [comment]
> What's your username on the old forum, @mic4ael? https://forum.sentry.io/u/mic4ael/ is 404.

Hey, it is crossner90 :) https://forum.sentry.io/u/crossner90/

**Comment by chadwhitacre** [comment]
I bumped this internally.

**Comment by chadwhitacre** [comment]
`forum.sentry.io` is a CNAME to `sentry.bydiscourse.com`, not sure what's going to be possible here.

Tracking down access ...

**Comment by chadwhitacre** [comment]
I emailed team@discourse.org.

**Comment by chadwhitacre** [comment]
> If you would like us to take the site out of read only mode so you can login and access the site, just let us know and we can make this change for you on our end.

**Comment by chadwhitacre** [comment]
Saving this for when I put it back into read-only mode:

> 🛑 Why is this site in read only mode? 🛑 Because we've moved to GitHub Discussions, that's why.
Please find us in the [sentry repo](https://github.com/getsentry/sentry/discussions) for product topics or the [relevant SDK or other repo](https://github.com/orgs/getsentry/repositories) for other topics. Thanks.

**Comment by mic4ael** [comment]
Hey @chadwhitacre is there anything I need to do now?

**Comment by chadwhitacre** [comment]
I confirmed (by looking at Git history in indico/newdle that the email on the crossner90 forum account is associated with your GitHub account. I've deleted the crossner90 forum account, including all posts from the account.

**Comment by chadwhitacre** [comment]
I put the site [back into read-only mode](https://meta.discourse.org/t/enabling-a-read-only-mode/152970). The jokes keep coming:

<img width="478" alt="kek" src="https://user-images.githubusercontent.com/134455/216087359-ae04df18-23a2-400a-8d8d-2d05462937ab.png">

**Comment by chadwhitacre** [comment]
I've left notes [in Notion](https://www.notion.so/sentry/forum-sentry-io-a441ce4adc174ae4af0705ecd32773c4).

> We get these weird fails on direct access to forum links.

If/when I see this again I'll try to remember to email team@discourse.org about it.

Calling this done.

Cheers! :-)
