### ISSUE TITLE
Breakdown for filed GH issues per team

### ISSUE THREAD

**Issue by armenzg** [getsentry/team-ospo#82]
Hi!
I would like to measure the percentage of tickets which are filed for our teams to investigate on a month per month basis (Ecosystem team).

I want to have an initiative to reduce the burden of issues with integrations.

Do you have this information? Thanks!

**Comment by chadwhitacre** [comment]
This should be doable with advanced GitHub searches using the `Team: *` labels, no?

**Comment by armenzg** [comment]
That's correct. I managed to see that we have 1/7 issues assigned to our team.
