### ISSUE TITLE
Migrate all github actions -> eng-pipes

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#84]
Routing issues has been moved to eng-pipes [here](https://github.com/getsentry/team-ospo/issues/58).
Let's do that also for these files:
- [ ] `stale.yml`.

**Comment by chadwhitacre** [comment]
Stalebot we may as well keep as an action. It's a third-party thing that would be fairly complex to reimplement, and the real-time response isn't as important as w/ routing and triage.

Status helper should def be moved.

**Comment by chadwhitacre** [comment]
We whacked [status helper](https://github.com/getsentry/team-ospo/issues/107#issuecomment-1447026559).

Looks like we're done here, since we're keeping stalebot where it is.
