### ISSUE TITLE
Enable routing for GTM teams

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#86]
Enable routing for GTM teams. They represent external customers and the eng-pipes bot shouldn't ignore issues that are created from these sentry users.

For all routing and triage operations GTM should be considered external/community.

For [401](https://sentryio.cloud.looker.com/dashboards/401) they should be considered "Company" (internal) or a third bucket.

**Comment by chadwhitacre** [comment]
Moving to PR in https://github.com/getsentry/eng-pipes/pull/386.

**Comment by hubertdeng123** [comment]
this team perhaps?
https://github.com/orgs/getsentry/teams/gtm
