### ISSUE TITLE
More developed `Waiting for: *` label logic

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#98]
- [x] https://github.com/getsentry/eng-pipes/pull/475
- [x] https://github.com/getsentry/eng-pipes/pull/477
- [x] https://github.com/getsentry/eng-pipes/pull/480
- [x] https://github.com/getsentry/eng-pipes/pull/488
- [x] https://github.com/getsentry/eng-pipes/pull/492

**Comment by chadwhitacre** [comment]
Everything is looking fine, closing for Hubert while he's on his phone. :)
